### ISSUE TITLE
Randomly teleporting up to 2500 blocks away while exploring, anyone know why? 

### ISSUE THREAD

**Issue by melvindacleaner** [AllTheMods/ATM-4#129] opened 2020-01-25 03:04 UTC
I made a new world, started exploring within about 4 or 5 minutes I randomly got teleported 1800 blocks away, within a few minutes it happened again. This time i was deep underground, finally made my way to the surface in as few pieces as possible. Within 2 minutes I randomly teleported 2500 blocks away to yet another completely unwanted random destination. Does anyone know which mod this is being caused by so i can disable it via config or just delete the mod because it's made the game completely miserable and pointless to play. Any help would be greatly appreciated :(

Edit: I forgot to mention I'm using the latest version.

**Comment by conabung** [comment] 2020-01-25 13:40
I have the same problem. Everytime i've found a place to settle down i get teleported 2000+ blocks away, its so frustrating. I tried playing on different worlds to see if that fixed the problem, but it happens on every single one of them. I hope it gets fixed/figured out soon :(

**Comment by Asshall** [comment] 2020-01-26 10:03
Are you teleported to random places or structures ? It happens to me as well but only to structures...

**Comment by melvindacleaner** [comment] 2020-01-26 10:12
Sometimes to structures, or at least so it seemed, because often there would be a structure nearby, but sometimes to seemingly random underground caves that didn't appear to contain anything out of the ordinary.

Side note not connected necessarily to fixing the issue directly but I did discover there is an ATM 5 pack now and tried that. So far I haven't been randomly teleported anywhere playing on the new pack.

**Comment by LezChap** [comment] 2020-01-26 16:49
So I got a seed and coords that a player was having this happen in, and able to reproduce in a new world with the same seed.  I tried the seed/coords and was unable to replicate there...but it was near a multi-ravine and large cave system, so I flew around in creative until I found a place that would teleport me.  The same place -always- teleports me, and always teleports me to the same coordinates.  Very odd.  
The seed I used: 6087916787040913555 with world type of BiomesOPlenty
The coords that worked for me to trigger this teleportation: -250, 39, 2090 (a vertical cave shaft with a single lava source that'll flow down).

I'm currently working on tracking down which mod is causing this.  Those coords did not teleport in v0.3.2 of the pack, only v0.3.3...so it was one of the added or updated mods.  Removing the new mods in 0.3.3 didn't stop the teleport, so I deactivated most of the updated mods (list: aiotbotania due to dependency, Botania, CookingForBlockheads, CraftingTweaks, Cyclic, FarmingForBlockheads, LostCities, MaEssentials, MysticalAgriculture, PotionsMaster, RefinedRelocation, SilentsMechanisms, Tombstone, Waystones).  The world stopped doing the teleport thing, but after reactivating all mods in batches to try to isolate, it still didn't teleport...but a new world with the same seed still would.  This seems to indicate one of the removed blocks/tiles/entities from when I disabled all the mods is causing this...working on narrowing it down further, but that's where I'm at right now.

Unless it's a weird conflict between two or more mods, I have ruled out the following as the source of the issue:
LostCities
Waystones
Tombstone
Silent'sMechanisms
RefinedRelocation

Okay, seems like Potions Master is involved somehow, trying a few fixes...

**Comment by LezChap** [comment] 2020-01-26 18:05
ALRIGHT:  The fix is in...you gotta rollback to an older version of Potions Master...this is the most recent working version as of this post: https://www.curseforge.com/minecraft/mc-mods/potionsmaster/files/2860505
That is the links for potionsmaster-0.0.5-1.14.4-28.1.114.jar

The next version, which is the one in version 0.3.3 of the pack, implements a "Fast Travel" potion which teleports you to the nearest structure of a given type (the patchnotes give Village as an example).  I'm guessing this is, for some reason, applying to players when it shouldn't be.  There is one more updated version released, that says it uses updated mappings, but the "random teleport" issue is still happening in it, so don't go with it.

**Comment by LezChap** [comment] 2020-01-27 05:38
Another update:  The mod dev pushed a new version since my last post that should also fix this error, as well as the NoSuchMethod errors that are crashing some users:
https://www.curseforge.com/minecraft/mc-mods/potionsmaster/files/2870090
potionsmaster-0.0.8-1.14.4-28.1.109.jar

The dev's been working hard all evening since hearing of the random teleport issue trying to resolve it.

**Comment by whatthedrunk** [comment] 2020-01-27 16:36
Pushed a hotfix update that just updated the mod to fix it.

**Closed as completed by whatthedrunk** 2020-01-27 16:36 UTC
