### ISSUE TITLE
ATM4 v1.1, MC1.14.4 - Client shows "incompatible FML modded server" but still works

### ISSUE THREAD

**Issue by mbouffa** [AllTheMods/ATM-4#138] opened 2020-03-20 21:50 UTC
Player Client - Forge 28.2.3

On the client launcher when in server selection screen, my ATM4 server shows a Red X with tooltip "incompatible FML modded server", but is still able to launch correctly.

I am launching player client using Twitch Launcher.
Server files downloaded from https://www.curseforge.com/minecraft/modpacks/all-the-mods-4, using Server Pack files from Mar 10, 2020.

Comparing the Client and Server mod folder, the delta is 2 packages: [dynviewdist-1.3, LLOverlayReloaded-1.2.4-mc1.14.4]

If I delete these from my player client mod folder, the red X goes away. 

RESOLUTION: Remove these two packages from client mod set until they are available for server side?

**Comment by furtabs** [comment] 2020-03-21 04:03
Duplicate of #134

**Closed as completed** 2020-03-21 04:02 UTC
